[package]
edition = "2018"
name = "game-of-life"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.33"
console_error_panic_hook = "0.1.5"
nom = "4.2.0"
rand = "0.6.5"
